epichomes/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace epichomes.Controllers
{
    public class AboutController:Controller
    {
        private readonly ILogger<AboutController> _logger;

        public AboutController(ILogger<AboutController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

epichomes/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;

namespace epichomes.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

epichomes/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;

namespace epichomes.Controllers
{
    public class RestaurantController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

epichomes/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Mvc;

namespace epichomes.Controllers
{
    public class RoomsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

epichomes/Views/Shared/Components/_header.cshtml
@page
@using epichomes.Views.Shared.Components
@* @model _headerModel
 *@@{
}

<link rel="stylesheet" href="~/css/header.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/datepickerstyles.css" asp-append-version="true" />

<header>
    <nav class="headercon">
            <a class="myheadertext" asp-area="" asp-controller="Home" asp-action="Index">Epichomes</a>
            <ul class="mymenu">
                <li>
                    <a class="" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    <a class="" asp-area="" asp-controller="About" asp-action="Index">About</a>
                </li>
                <li>
                    <a class="" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                </li>
                <li>
                    <a class="" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurant</a>
                </li>
                <li>
                    <a class="" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                </li>
            </ul>
            <div class="menunum">
                <p>+1 002 132 444</p>
                <div class="menuicon">

                <i class="fa fa-bars menuicon" aria-hidden="true"></i>
                </div>
            </div>

    </nav>
    <div class="headercontent">
        <div class="contentcon">
            <h1 class="slogan">Beyond Hospitality, It's a Lifestyle.</h1>
            <h2 class="c2a">Find your perfect stay with ease and explore a wide range of rooms. Book your Ideal gateway to Luxury </h2>

        </div>
        <div class="bookingcon">
            <div class="booking">
                <div class="bookingoption">
                    <div class="bookingselection">
                        <ion-icon name="location-outline"></ion-icon>                        
                        <p>Location <i class="fa fa-angle-down" aria-hidden="true"></i></p>
                    </div>
                    <input class="datepickerinput" placeholder="where are you going?" type="text">

                </div><div class="bookingoption">
                    <div class="bookingselection">
                        <ion-icon name="calendar-outline"></ion-icon>                    
                        <p>Check In <i class="fa fa-angle-down" aria-hidden="true"></i></p>
                    </div>
                    <input class="datepickerinput" type="text" id="datepicker">

                </div>
                <div class="bookingoption">
                    <div class="bookingselection">
                        <ion-icon name="calendar-outline"></ion-icon>
                    <p>Check Out <i class="fa fa-angle-down" aria-hidden="true"></i></p>
                    </div>
                    <input class="datepickerinput" type="text" id="datepicker2">
                </div>
                <div class="bookingoption">
                    <div class="bookingselection">
                        <ion-icon name="person-outline"></ion-icon>                   
                        <p>Persons <i class="fa fa-angle-down" aria-hidden="true"></i></p>
                    </div>
                    <select class="persons">
                        <option>1 person</option>
                        <option>2 persons</option>
                    </select>
                </div>
                <div class="book">
                    Book Now
                </div>
            </div>
        </div>

    </div>
</header>

epichomes/Views/Shared/Components/imagecard.cshtml
@page
@model epichomes.Views.Shared.Components.imagecardModel
@{
    var rating = 4;
}

<style>
  .cardcontainer{
      display: flex;
      flex-direction:column;
      width: 250px;
      height: 300px;
      border-radius: 10px;
      border: 1px solid #e8e8e8;
  }
  img{
      width: 100%;
      height: 200px;
      border-top-left-radius: 10px;
      border-top-right-radius: 10px;
  }
  .ratingcon i{
      color: gold;
  }
  .ratingcon{
      display: flex;
      flex-direction: row;
      align-items: center;
      gap: 5px;
  }
  .content{
      flex: 1;
  }
</style>


<div class="cardcontainer">
    <img src="/images/apartment.jpg" alt="" />
    <div class="content">
        <p>Deluxe Room</p>
        <div>
            @switch (rating)
            {
                case 1:
                    <div class="ratingcon">
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </div>
                    break;
                case 2:
                    <div class="ratingcon">
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </div>
                    break;
                case 3:
                    <div class="ratingcon">
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </div>
                    break;
                    case 4:
                    <div class="ratingcon">
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </div>
                    break;
                    case 5:
                    <div class="ratingcon">
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                    
                    </div>
                    break;
            
            }
        </div>
        <p>Sao Francisco</p>
    </div>
</div>